package euler

import "fmt"

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

func main() {
	fmt.Println(findSum())
}

func findSum() int {

	f := fibonacci()
	sum := 0

	for true {
		v := f()
		if v < 4000000 {
			if v%2 == 0 {
				sum += v
			}
		} else {
			break
		}
	}

	return sum
}

func fibonacci() func() int {
	x, y := 0, 1
	return func() int {
		x, y = y, x+y
		return x
	}
}
